project_setup_task:
  description: >
    Set up a new React project, prompt for the project name, and install Tailwind, react-hook-form, react-router-dom, axios, and humanize-string.
  expected_output: >
    A new React project with the required packages installed, including a .tool-versions file specifying nodejs 22.7.0.
  agent: project_creator

context_creation_task:
  description: >
    Create a context for state management. Prompt the user for the context name and replace instances of "Project" with the provided name.
  expected_output: >
    A new context file in src/context using the provided name.
  agent: context_builder

component_setup_task:
  description: >
    Recreate the Navbar component, integrating with the context created earlier.
  expected_output: >
    A functional Navbar component that interacts with the newly created context.
  agent: component_builder

form_creation_task:
  description: >
    Prompt the user for form fields (label, field_name, field_type) and generate a ProjectForm component with these fields.
  expected_output: >
    A form component with dynamic fields as specified by the user.
  agent: field_creator

project_listing_task:
  description: >
    Recreate the Projects component to display project-related information based on the created context and form data.
  expected_output: >
    A component that lists projects dynamically based on user input.
  agent: component_builder
